### ISSUE TITLE
トレーニング効果のコピー

### ISSUE THREAD

**Issue by copios** [copios-jp/red-falcon#27]
とりあえず、ネットから仮コピーを入れていますが、リリース前にHeartLimit独自のコピーが必要です。

- [ ] - (青）有酸素能力の基礎作り・ビギナーの初期トレーニング。ウォームアップやクールダウン、回復を助ける。
- [ ] - (緑）有酸素能力の向上・効果的な脂肪燃焼効果。基礎的な身体能力を向上させ、回復を促進、新陳代謝を増進させる
- [ ] - (黄色）マラソントレーニングに適している・有酸素能力の更なる向上。一般的なトレーニングペースの強化。中強度の運動をより容易にし、運動効率を改善する。
- [ ] - (オレンジ）無酸素性能力の向上・乳酸耐性の向上。早い速度での持久力を維持する力を向上。
- [ ] - (赤）最大酸素摂取量の向上・速度・筋力の向上・上級者向けレベル。呼吸および筋肉への最大またはそれに準ずる負荷

#9

**Comment by 7131Masa** [comment]
（青）トレーニング前後のストレッチや柔軟体操効果を高め、ウォームアップやクールダウンで代謝促進や疲労回復をする。

**Comment by 7131Masa** [comment]
（緑）呼吸をしっかりしながらトレーニングをする事で脂肪燃焼効果が上がり、基礎体力の向上、代謝の促進でダイエット効果が上がる。

**Comment by 7131Masa** [comment]
（黄色）血流の流れが早くなり身体全身に酸素を運びダイエット効果をさらに上げていきます。有酸素運動の効果も上がり、トレーニングレベルも向上します。

**Comment by 7131Masa** [comment]
（オレンジ色）トレーニング強度が上がり筋肥大、心肺機能の向上、消費カロリーも高くなり、筋肉をつけるシェイプアップ効果が上がります。

**Comment by 7131Masa** [comment]
（赤）心肺機能の90パーセントを超えるアスリートレベルのゾーンです。短時間で筋肉にかかる負担も強く筋肥大、筋力アップをします。
